security:

    encoders:
        App\Entity\User: 'sodium'

    providers:
        users_in_memory: { memory: null }
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
